api_platform:
    title: Cheeper API
    show_webby: false
    mapping:
        paths:
            - '%kernel.project_dir%/src/App/API/Resources'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
