framework:
    messenger:
        failure_transport: failed_messages
        default_bus: none.bus
        buses:
            none.bus:
                default_middleware: allow_no_handlers
            command.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
            projection.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
            query.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
        transports:
            async_commands: '%env(MESSENGER_TRANSPORT_BASE_DSN)%/commands'
            sync_commands: 'sync://'
            events: '%env(MESSENGER_TRANSPORT_BASE_DSN)%/events'
            query: 'sync://'
            failed_messages: '%env(MESSENGER_TRANSPORT_BASE_DSN)%/failed-messages'
            projections: '%env(MESSENGER_TRANSPORT_BASE_DSN)%/projections'

            chapter7_sync_commands: 'sync://'
            chapter7_async_commands: '%env(MESSENGER_TRANSPORT_BASE_DSN)%/chapter7_commands'
            chapter7_events: '%env(MESSENGER_TRANSPORT_BASE_DSN)%/chapter7_events'
            chapter7_sync_queries: 'sync://'
            chapter7_sync_projections: 'sync://'
            chapter7_async_projections: '%env(MESSENGER_TRANSPORT_BASE_DSN)%/chapter7_projections'
            chapter7_failed_messages: '%env(MESSENGER_TRANSPORT_BASE_DSN)%/chapter7_failed_messages'
        routing:
            # Consider Signing up an Author is a sync command.
            # With a proper UX, almost all the commands should
            # be run asynchronously.
            # TODO: Review this comment

            # Domain Events are sent to asynchronous
            # transport to be processed later.
            Cheeper\AllChapters\DomainModel\DomainEvent: [events, projections]

            # Chapter 4
            Cheeper\Chapter4\Application\Author\Command\SignUpWithoutEvents\SignUpCommand: async_commands

            # Chapter 5
            # Queries are executed synchronously
            # in the same request that data is requested.
            Cheeper\Chapter5\Application\Query\Query: query

            # Chapter 6
            Cheeper\Chapter6\Application\Author\Command\FollowCommand: async_commands

            # End of Chapter 6

            # Chapter 7
            Cheeper\Chapter7\Application\Command: chapter7_sync_commands
            Cheeper\Chapter7\DomainModel\DomainEvent: chapter7_events
            Cheeper\Chapter7\Application\Projection: chapter7_async_projections
            Cheeper\Chapter7\Application\Query: chapter7_sync_queries
            # End of Chapter 7