version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: db
  app:
    build: .docker/php
    env_file: .env.docker.dist
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html