version: '3.9'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: db
  app:
    build: .docker/php
    init: true
    env_file: .env.docker.dist
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
  async-commands-consumer:
    build: .docker/php-cli
    profiles: ["async-commands"]
    init: true
    env_file: .env.docker.dist
    working_dir: /var/www/html
    command: "php bin/console messenger:consume commands_async -vv"
    volumes:
      - ./:/var/www/html
  async-events-consumer:
    build: .docker/php-cli
    profiles: ["async-events"]
    init: true
    env_file: .env.docker.dist
    working_dir: /var/www/html
    command: "php bin/console messenger:consume events_async -vv"
    volumes:
      - ./:/var/www/html
  async-projections-consumer:
    build: .docker/php-cli
    profiles: ["async-projections"]
    init: true
    env_file: .env.docker.dist
    working_dir: /var/www/html
    command: "php bin/console messenger:consume projections_async -vv"
    volumes:
      - ./:/var/www/html