# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            Cheeper\DomainModel\Cheep\Cheeps $cheeps: '@Cheeper\Infrastructure\Persistence\DoctrineOrmCheeps'
            Cheeper\DomainModel\Author\Authors $authors: '@Cheeper\Infrastructure\Persistence\DoctrineOrmAuthors'
            Cheeper\DomainModel\Author\Authors $authorsRepository: '@Cheeper\Infrastructure\Persistence\DoctrineOrmAuthors'
            Cheeper\DomainModel\Follow\Follows $follows: '@Cheeper\Infrastructure\Persistence\DoctrineOrmFollows'
            Symfony\Component\Messenger\MessageBusInterface $commandBus: "@command.bus"
            Symfony\Component\Messenger\MessageBusInterface $queryBus: "@query.bus"
            Symfony\Component\Messenger\MessageBusInterface $eventBus: "@event.bus"
            Cheeper\Chapter6\Application\Event\EventBus: '@Cheeper\Chapter6\Infrastructure\Application\Event\SymfonyEventBus'
            Cheeper\Chapter5\Application\Query\QueryBus: '@Cheeper\Chapter5\Infrastructure\Application\Query\SymfonyQueryBus'
            Architecture\CQRS\App\Repository\FollowersRepository: '@Architecture\CQRS\Infrastructure\Persistence\Doctrine\DoctrineFollowersRepository'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App/*'
        exclude: '../src/App/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Helpers}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/App/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\ArgumentResolver\UuidResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 200 }

    Predis\ClientInterface:
        class: 'Predis\Client'

    ApiPlatform\Core\Bridge\RamseyUuid\Identifier\Normalizer\UuidNormalizer:
        tags:
            - { name: api_platform.identifier.denormalizer }

    Cheeper\Infrastructure\:
        resource: '../src/Cheeper/Infrastructure/**/*.php'

    Cheeper\Application\Command\:
        resource: '../src/Cheeper/Application/Command/**/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    Cheeper\Chapter5\Application\Query\:
        resource: '../src/Cheeper/Chapter5/Application/Query/**/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: query.bus }

    Cheeper\Chapter6\Infrastructure\:
        resource: '../src/Cheeper/Chapter6/Infrastructure/**/*.php'

# CHAPTER 5
    Cheeper\Chapter5\Infrastructure\Application\Query\SymfonyQueryBus: ~
    Architecture\CQRS\Infrastructure\Persistence\Doctrine\DoctrineFollowersRepository: ~

# CHAPTER 6
#    Cheeper\Chapter6\Infrastructure\Application\Projector\Author\SymfonyAuthorFollowedHandler:
#        resource: '../src/Cheeper/Infrastructure/**/*.php'

    Cheeper\Chapter6\Application\Projector\Author\CountFollowerProjector: ~

    Cheeper\Chapter6\Application\Command\Author\WithDomainEvents\FollowHandler:
        tags:
            - { name: messenger.message_handler, bus: command.bus }
        class: 'Cheeper\Chapter6\Application\Command\Author\WithDomainEvents\FollowHandler'

    Cheeper\Chapter6\Infrastructure\Application\Projector\Author\SymfonyCountFollowerProjector:
        tags:
            - { name: messenger.message_handler, bus: command.bus }
        arguments:
            - '@Cheeper\Chapter6\Application\Projector\Author\CountFollowerProjector'

    Cheeper\Chapter6\Infrastructure\Application\Projector\Author\SymfonyAuthorFollowedHandler:
        tags:
            - { name: messenger.message_handler, bus: event.bus }
        class: 'Cheeper\Chapter6\Infrastructure\Application\Projector\Author\SymfonyAuthorFollowedHandler'

