# snippet inject-command-bus-services
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: "@command.bus"

    #ignore
    App\:
        resource: '../src/App/*'
        exclude: '../src/App/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Helpers}'
    App\Controller\:
        resource: '../src/App/Controller'
        tags: ['controller.service_arguments']
    #end-ignore
# end-snippet
