# file: config/packages/messenger.yaml
framework:
    messenger:
        failure_transport: failed_messages
        default_bus: none.bus
        buses:
            none.bus:
                default_middleware: allow_no_handlers
            command.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
            query.bus:
                middleware:
                    - validation
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation

        transports:
            # Command Transports
            commands_async: '%env(MESSENGER_TRANSPORT_BASE_DSN)%/commands'
            commands_sync: 'sync://'

            # Event Transports
            events_async: '%env(MESSENGER_TRANSPORT_BASE_DSN)%/events'
            events_sync: 'sync://'

            # Query Transports
            # It makes no sense to queries to
            # have an asynchronous transport. It has
            # to be synchronous so the customer can
            # get back the response.
            queries_sync: 'sync://'

            # Dead letter box
            failed_messages: '%env(MESSENGER_TRANSPORT_BASE_DSN)%/failed_messages'

        routing:
            # With a proper UX, almost all the commands should
            # be run asynchronously.
            Cheeper\Chapter4\Application\Command: commands_async

            # However, some commands can be defined to
            # be run synchronously.
            Cheeper\Chapter4\Application\Author\Command\SignUpCommand: commands_sync

            # Events can be run synchronously, however
            # all the benefits like performance and
            # transaction isolation come when using
            # the asynchronous transport.
            Cheeper\Chapter4\DomainModel\DomainEvent: events_async

            # Queries must be synchronous. Their responses
            # need to be back to the customers.
            Cheeper\Chapter5\Application\Query: queries_sync