name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup system virtual memory
        run: sudo sysctl -w vm.max_map_count=262144

      - name: Install latest docker version
        run: |
            apt-get update
            apt-get remove docker docker-engine docker.io containerd runc
            apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            apt-get update
            apt-get install docker-ce docker-ce-cli containerd.io

      - name: Check static analysis
        run: make ci-analysis

      - name: Run tests
        run: make ci-tests

      - name: Run Infection
        run: make ci-infection
